# Generated by Django 6.0.4 on 2026-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('GR', 'Gramas'), ('LT', 'Litro'), ('ML', 'Mililitro'), ('CX', 'Caixa'), ('PC', 'Peça')], default='un', max_length=10)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
            },
        ),
    ]
