# Generated by Django 6.0.4 on 2026-04-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='hospede_principal',
            field=models.ForeignKey(limit_choices_to={'eh_principal': True}, on_delete=django.db.models.deletion.CASCADE, related_name='estadia_principal', to='hospedagem.hospede'),
        ),
    ]
